# Generated by Django 5.1.2 on 2024-11-03 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("staff_number", models.IntegerField()),
                ("name", models.CharField(max_length=100)),
                ("Team", models.CharField(max_length=100)),
                ("Facility", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Exam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("difficulty_rating", models.IntegerField()),
                ("max_difficulty", models.IntegerField()),
                ("weight", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="ExamScore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score", models.FloatField()),
                ("weighted_score", models.FloatField()),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="weightscore.employee",
                    ),
                ),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="weightscore.exam",
                    ),
                ),
            ],
        ),
    ]
