# Generated by Django 5.1.2 on 2024-11-04 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("weightscore", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="staff_number",
            field=models.CharField(max_length=300),
        ),
    ]
