# Generated by Django 5.1.2 on 2024-11-14 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("weightscore", "0002_alter_employee_staff_number"),
    ]

    operations = [
        migrations.RenameField(
            model_name="exam",
            old_name="name",
            new_name="Exam",
        ),
    ]
