# Generated by Django 5.1.2 on 2024-11-14 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("weightscore", "0003_rename_name_exam_exam"),
    ]

    operations = [
        migrations.RenameField(
            model_name="exam",
            old_name="Exam",
            new_name="exam_name",
        ),
    ]
