# Generated by Django 5.1.2 on 2024-11-14 07:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("weightscore", "0004_rename_exam_exam_exam_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="examscore",
            name="exam_date",
            field=models.DateField(default=datetime.date.today),
        ),
    ]
