# Generated by Django 5.1.2 on 2024-11-17 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("weightscore", "0005_examscore_exam_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="designation",
            field=models.CharField(default="Technician", max_length=100),
        ),
        migrations.AlterField(
            model_name="examscore",
            name="weighted_score",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
