# Generated by Django 5.1.2 on 2024-11-18 08:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("weightscore", "0006_employee_designation_alter_examscore_weighted_score"),
    ]

    operations = [
        migrations.CreateModel(
            name="TrainingModule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("code", models.CharField(max_length=10, unique=True)),
                ("category", models.CharField(default="equipment", max_length=20)),
                (
                    "file",
                    models.FileField(
                        blank=True, null=True, upload_to="Training/uploads/"
                    ),
                ),
                ("facility", models.CharField(max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("total_pages", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="CompletedTraining",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_completed",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="completed_trainings",
                        to="weightscore.employee",
                    ),
                ),
                (
                    "training_module",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="completed_by_profiles",
                        to="weightscore.trainingmodule",
                    ),
                ),
            ],
            options={
                "ordering": ["-date_completed"],
                "unique_together": {("employee", "training_module")},
            },
        ),
    ]
