# Generated by Django 5.1.2 on 2024-11-18 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("weightscore", "0007_trainingmodule_completedtraining"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trainingmodule",
            name="category",
            field=models.CharField(default="EQUIPMENT MANUAL", max_length=20),
        ),
    ]
