# Generated by Django 5.1.2 on 2024-11-24 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("weightscore", "0008_alter_trainingmodule_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="Required_Module_trainings",
            field=models.IntegerField(default=18),
        ),
        migrations.AddField(
            model_name="employee",
            name="Required_exams",
            field=models.IntegerField(default=14),
        ),
        migrations.AlterField(
            model_name="examscore",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="completed_Exams",
                to="weightscore.employee",
            ),
        ),
    ]
